### PR TITLE
Auto Recovery Dashboard Should Use Sum Instead of Count for Total Bytes

### PR DESCRIPTION
**Pull request by michaeljmarshall**
The recovery dashboard has a panel titled `Replication read throughput (bytes/s)` and `Replication write throughput (bytes/s)`. Each of these use the `count` metric instead of the `sum` metric. Given that we want to know how many bytes have been read or written, we want the total bytes, not the number of times the metric has been incremented.

Further, I updated the units to bytes on the y-axis of each panel, and I set the minimum to 0 because it is a rate on an increasing counter, so it'll always be non-negative.

### CODE REVIEW

**Comment by michaeljmarshall** [comment]
@sijie - is there a process in place to update these dashboards? Thanks!

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@michaeljmarshall sorry that we missed this pull request. the change looks good to me. 

You can bump the version number in the VERSION file. It will automatically build and publish a new image.

**Comment by michaeljmarshall** [comment]
@sijie - no worries, I just wanted to follow up on it. I bumped the VERSION. It's ready to merge.

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@michaeljmarshall Cool. I have just merged this pull request.

**Pull request merged**
