### PR TITLE
feat: add dashboard for connector sink&source and enhance templating …

### PR DESCRIPTION
**Pull request by rockybean**
…variable setting for cascading filter works

Relative ticket is https://github.com/streamnative/support-tickets/issues/122

### CODE REVIEW

**Comment by rockybean** [comment]
The dashboard is like below.
image

**Comment by rockybean** [comment]
@addisonj PTAL ❤️

**Comment by rockybean** [comment]
@addisonj PTAL

**Review by addisonj — APPROVED** [review]
LGTM, I haven't run them though

**Pull request merged**
